import { VERSION } from '../constant/config';

const head = `<span style="color: #D0CAE0;"><b>
——————————————————————————— 迷迭香 𝕽𝖔𝖘𝖒𝖆𝖗𝖎𝖓 ${VERSION} ———————————————————————————
 ######     #####     #####    ##   ##      ##     ######    ######   ##   ##  
  ##  ##   ##   ##   ##   ##   ### ###     ####     ##  ##     ##     ###  ##  
  ##  ##   ##   ##   ##        #######    ##  ##    ##  ##     ##     #### ##  
  #####    ##   ##    #####    ## # ##    ######    #####      ##     ## ####  
  ####     ##   ##        ##   ##   ##    ##  ##    ####       ##     ##  ###  
  ## ##    ##   ##   ##   ##   ##   ##    ##  ##    ## ##      ##     ##   ##  
 ###  ##    #####     #####    ##   ##    ##  ##   ###  ##   ######   ##   ##
—————————————————————————————— 半自动 Screeps AI ——————————————————————————————
</b></span>`;

const br = '<br>';
const line = (text = '────────────────────────────────────────────────') =>
    `<span style="color:#3b3b3b">${text}</span>`;
const title = (emoji: string, text: string) =>
    `<span style="color:#D0CAE0"><b>${emoji} ${text}</b></span>`;
const cmd = (text: string) => `<span style="color:#9CDCFE"><b>${text}</b></span>`;
const sub = (emoji: string, text: string) => `<span style="color:#C8C8C8"><b>${emoji} ${text}</b></span>`;

/** 帮助文本配置 */
const helpTexts: Record<string, string> = {
    help: [
        title('🚀', '启动流程'),
        `0) ${cmd('room.start(roomName, layout?)')}：快速启动房间（一条指令执行完整流程）`,
        `- roomName：房间名；layout：布局名称(留空使用自动布局)；`,
        `- 如果有centerPos旗帜则会设置布局中心, 如果使用静态布局则必须要有这个旗帜`,
        `1) ${cmd('room.add(roomName, layout?, x?, y?)')}：添加房间到控制列表（列表中的房间才会自动运行）`,
        `2) ${cmd('layout.visual(roomName, layout?)')}：查看房间布局可视化预览`,
        `3) ${cmd('layout.build(roomName, layoutType?)')}：生成房间建筑位置并保存到 Memory`,
        `- layoutType：可选；传入则覆盖 RoomData.layout，并覆盖布局内存；不传则用当前设置且不覆盖布局内存`,
        `4) ${cmd('layout.auto(roomName, enable?)')}：开关房间自动建筑`,
        `- enable：是否开启自动建筑（如果不传入则会根据当前状态切换）`,
        line(),
        title('📚', '指令列表'),
        `- ${cmd('helpRoom')}：房间相关指令`,
        `- ${cmd('helpLayout')}：布局相关指令`,
        `- ${cmd('helpInfo')}：信息相关指令`,
        `- ${cmd('helpMine')}：外矿相关指令`,
        `- ${cmd('helpRoad')}：外矿道路相关指令`,
        `- ${cmd('helpMarket')}：市场交易指令`,
        `- ${cmd('helpLab')}：Lab 相关指令`,
        `- ${cmd('helpFactory')}：Factory 相关指令`,
        `- ${cmd('helpPower')}：Power 相关指令`,
        `- ${cmd('helpSpawn')}：孵化相关（控制台/旗帜）`,
        `- ${cmd('helpExpand')}：扩张相关指令`,
        `- ${cmd('helpNuke')}：核弹（旗帜/控制台）`,
        `- ${cmd('helpTeam')}：Team 小队系统`,
        `- ${cmd('helpTerminal')}：Terminal 相关指令`,
        `- ${cmd('helpResource')}：资源管理指令`,
        `- ${cmd('helpOther')}：其他指令`,
        line(),
    ].join(br),

    helpRoom: [
        title('🏠', '房间指令列表'),
        line(),
        `${cmd('room.start(roomName, layout?)')}：快速启动房间`,
        `${cmd('room.add(roomName, layout?, x?, y?)')}：添加房间到控制列表`,
        `- roomName：房间名；layout：布局；x,y：布局中心`,
        `- layout：使用的布局（留空则不使用）`,
        `- x,y：布局中心坐标（留空则不使用，如果有centerPos旗帜则会自动设置）`,
        `- 手动布局：需保证 storage / terminal / factory / 1 个 link 集中放置，与这四个建筑均相邻的点位为中心（中央搬运工位置）`,
        `${cmd('room.remove(roomName)')}：从控制列表删除房间`,
        `${cmd('room.list()')}：查看控制列表`,
        `${cmd('room.mode(roomName, mode)')}：设置房间运行模式（main / stop / low）`,
        `${cmd('room.setcenter(roomName, x, y)')}：设置房间布局中心`,
        `${cmd('room.defendmode(roomName, mode)')}：设置房间防御模式`,
        `${cmd('room.sign(roomName, text?)')}：设置房间签名`,
        `${cmd('room.setram(roomName, hits)')}：设置刷墙上限（比例 0-1 或具体血量）`,
        `${cmd('room.send(roomName, targetRoom, type, amount)')}：添加资源发送任务`,
        line(),
    ].join(br),

    helpLayout: [
        title('🗺️', '布局指令列表'),
        line(),
        `${cmd('layout.set(roomName, layout, x, y)')}：设置房间布局（rosemary / clover / hoho / tea / scorpior）`,
        `${cmd('layout.auto(roomName)')}：开关房间自动建筑`,
        `${cmd('layout.remove(roomName)')}：删除指定房间布局 Memory`,
        `${cmd('layout.build(roomName, layoutType?)')}：生成建筑位置并保存到 Memory`,
        `- layoutType：可选；传入则覆盖 RoomData.layout，并覆盖布局内存；不传则用当前设置且不覆盖布局内存`,
        `- 示例：${cmd("layout.build('W1N1')")}（仅在无布局内存时生成）`,
        `- 示例：${cmd("layout.build('W1N1','auto')")} / ${cmd("layout.build('W1N1','63auto')")} / ${cmd("layout.build('W1N1','scorpior')")} / ${cmd("layout.build('W1N1','tea')")}（强制覆盖并切换布局）`,
        `- 静态布局：使用 centerPos 旗帜或手动设置来定位布局中心`,
        `- 未设置布局：将使用默认动态布局（auto）`,
        `- 指定布局为 63auto：将使用 63auto 动态布局`,
        `- 指定布局为 scorpior：将使用 scorpior 动态布局`,
        `- 无房间视野：需要设置 flag：pc（控制器）、pm（矿）、pa/pb（能量源）`,
        `${cmd('layout.visual(roomName, layout?)')}：显示布局可视化`,
        `${cmd('layout.save(roomName, struct?)')}：将房间建筑保存到布局 Memory`,
        `${cmd('layout.site(roomName, structType?)')}：根据布局 Memory 一键放满工地（到结构上限/工地上限）`,
        `${cmd('layout.ramhits(roomName)')}：查看 rampart 最小/最大血量`,
        `${cmd('layout.rampart(roomName, operate)')}：从 flag 添加/删除 rampart（layout-rampart；1 添加 / 0 删除）`,
        `${cmd('layout.wall(roomName, operate)')}：从 flag 添加/删除 wall（layout-wall）`,
        `${cmd('layout.ramwall(roomName, operate)')}：从 flag 添加/删除 rampart + wall（layout-ramwall）`,
        `${cmd('layout.ramarea(roomName, operate)')}：从区域添加/删除 rampart（layout-ramA / layout-ramB）`,
        line(),
    ].join(br),

    helpInfo: [
        title('ℹ️', '信息指令列表'),
        line(),
        `${cmd('info.room(roomName?)')}：查看房间工作状态（不填 roomName 显示所有房间）`,
        `${cmd('info.res()')}：查看所有资源储量`,
        `${cmd('info.roomres()')}：查看房间资源占用空间`,
        `${cmd('info.craft(filter?)')}：分析全局资源可合成产物（默认仅显示自动合成且可合成>0；支持过滤）`,
        `- filter=lab/factory：仅显示对应生产类型`,
        `- filter=T0/T1/T2/T3：仅显示对应等级的化合物（Lab）`,
        `- filter=0/1/2/3/4/5（数字或字符串）：仅显示对应等级的商品（Factory）`,
        `- filter=资源名/缩写：仅显示指定资源（即使不可合成/不在自动生产）`,
        line(),
    ].join(br),

    helpNuke: [
        title('�', '核弹（旗帜/控制台）'),
        line(),
        sub('�', '放旗触发'),
        `- 旗名：${cmd('nuke-<数量>')} 或 ${cmd('nuke_<数量>')}（例如 nuke-1 / nuke_3 / nuke-1-xxx）`,
        `- 可选：flag.memory.rooms=["W1N1","W2N2"] 限制发射房；flag.memory.amount 覆盖数量`,
        line(),
        sub('⌨️', '控制台'),
        `- ${cmd('nuker.launch(...rooms)')}：发射核弹（放置 nuke-* 旗在目标点）`,
        `- ${cmd('nuker.request(roomName, x, y, amount?, ttl?, ...rooms)')}：添加核弹请求（创建 nuke-* 旗）`,
        `- ${cmd('nuker.cluster(roomName, count?, ...rooms)')}：在目标房生成多点 nuke flags`,
        `- ${cmd('nuker.list()')} / ${cmd('nuker.cancel(id)')} / ${cmd('nuker.clear()')}`,
        line(),
    ].join(br),

    helpTeam: [
        title('👥', 'Team 小队系统'),
        line(),
        sub('🚩', '孵化指令旗（TEAM_...）'),
        `- 格式：${cmd('TEAM_<配置>_<孵化房>_N次数_T间隔')}`,
        `- 示例：${cmd('TEAM_A28/4_E12N34_N1_T1000')}`,
        `- 配置：对应 Team 配置名（例如 A28/4）`,
        `- 孵化房：必须是己方房间（否则会自动删旗）`,
        `- N：总孵化次数上限；不写视为一次性指令（派发一次后删旗）`,
        `- T：孵化间隔（tick）`,
        `- 常见失败：配置不存在 / boost 资源不足（会自动删旗）`,
        line(),
        sub('🏷️', '队伍标记旗（Team-...）'),
        `- ${cmd('Team-<teamID>')}：系统生成的队伍标记旗（队伍数据不存在会自动清理）`,
        line(),
    ].join(br),

    helpMine: [
        title('⛏️', '外矿指令列表'),
        line(),
        `${cmd('mine.add(roomName, targetRoom)')}：添加外矿房间`,
        `- 普通房间：添加到 energy 列表`,
        `- 过道房间：添加到 highway 监控列表`,
        `- 中间房间：添加到 centerRoom 采矿列表`,
        `${cmd('mine.remove(roomName, targetRoom)')}：删除外矿房间`,
        `${cmd('mine.list(roomName)')}：查看外矿列表`,
        `${cmd('mine.clearRoad(roomName)')}：清空外矿 Road 缓存`,
        `${cmd('mine.auto(roomName, type)')}：开关自动采集（type: power / deposit）`,
        `${cmd('mine.mapShow(homeRoom?)')}：大地图显示过道 power/deposit 配置连线`,
        `${cmd('mine.mapHide(homeRoom?)')}：关闭大地图过道 power/deposit 配置连线`,
        `${cmd('mine.power(roomName, targetRoom, num, boostLevel?, prNum?)')}：派出 Power 开采队（boostLevel: 0/1/2）`,
        `${cmd('mine.deposit(roomName, targetRoom, num)')}：派出 Deposit 开采队`,
        `${cmd('mine.cancel(roomName, targetRoom, type?)')}：取消开采任务`,
        `${cmd('road.help()')}：外矿造路规划相关`,
        line(),
    ].join(br),

    // 兼容旧别名：历史上帮助里写的是 helpOutmine
    helpOutmine: [
        title('⛏️', '外矿指令列表'),
        line(),
        `${cmd('mine.add(roomName, targetRoom)')}：添加外矿房间`,
        `- 普通房间：添加到 energy 列表`,
        `- 过道房间：添加到 highway 监控列表`,
        `- 中间房间：添加到 centerRoom 采矿列表`,
        `${cmd('mine.remove(roomName, targetRoom)')}：删除外矿房间`,
        `${cmd('mine.list(roomName)')}：查看外矿列表`,
        `${cmd('mine.clearRoad(roomName)')}：清空外矿 Road 缓存`,
        `${cmd('mine.auto(roomName, type)')}：开关自动采集（type: power / deposit）`,
        `${cmd('mine.mapShow(homeRoom?)')}：大地图显示过道 power/deposit 配置连线`,
        `${cmd('mine.mapHide(homeRoom?)')}：关闭大地图过道 power/deposit 配置连线`,
        `${cmd('mine.power(roomName, targetRoom, num, boostLevel?, prNum?)')}：派出 Power 开采队（boostLevel: 0/1/2）`,
        `${cmd('mine.deposit(roomName, targetRoom, num)')}：派出 Deposit 开采队`,
        `${cmd('mine.cancel(roomName, targetRoom, type?)')}：取消开采任务`,
        `${cmd('road.help()')}：外矿造路规划相关`,
        line(),
    ].join(br),

    helpRoad: [
        title('🛣️', '外矿道路命令帮助'),
        line(),
        `${cmd('road.recalc(homeRoom, targetRoom)')}：重新计算指定路线`,
        `${cmd('road.recalcAll(homeRoom?)')}：重新计算所有外矿路线（不填则全部房间）`,
        `${cmd('road.clear(homeRoom, targetRoom)')}：清除指定路线`,
        `${cmd('road.clearAll(homeRoom)')}：清除所有路线`,
        `${cmd('road.stats(homeRoom)')}：显示统计信息`,
        `${cmd('road.validate(homeRoom)')}：验证数据完整性`,
        `${cmd('road.clearCache()')}：清除 CostMatrix 缓存`,
        `${cmd('road.health(homeRoom)')}：检查道路健康状态`,
        `${cmd('road.show(homeRoom, targetRoom?)')}：显示道路可视化`,
        `${cmd('road.hide(homeRoom)')}：隐藏道路可视化`,
        `${cmd('road.help()')}：显示此帮助`,
        line(),
    ].join(br),

    helpMarket: [
        title('💱', '市场交易指令列表'),
        line(),
        `${cmd('market.deal(orderId, maxAmount?, roomName?)')}：直接交易订单`,
        `${cmd('market.deal(roomName, orderId, maxAmount?)')}：直接交易订单（更顺手的写法）`,
        `${cmd('market.look(resType, orderType, roomName?, length?)')}：查看市场订单（orderType 支持 buy/sell/买/卖；传 roomName 才能算综合单价）`,
        `${cmd('market.lookBuy(resType, roomName?, length?)')}：按“购买”视角查看（等价 look(resType, ORDER_SELL, ...)）`,
        `${cmd('market.lookSell(resType, roomName?, length?)')}：按“出售”视角查看（等价 look(resType, ORDER_BUY, ...)）`,
        `${cmd('market.buy({roomName, type, amount, price?, maxPrice?})')}：创建求购订单`,
        `${cmd('market.sell({roomName, type, amount, price?, minPrice?})')}：创建出售订单`,
        `${cmd('market.dealBuy(roomName, type, amount, length?, price?)')}：直接购买资源（amount 支持 10k/2m）`,
        `${cmd('market.dealSell(roomName, type, amount, length?, price?)')}：直接出售资源（amount 支持 10k/2m）`,
        `${cmd('market.dealBuy({roomName, type, amount, length?, price?})')}：直接购买资源（对象参数写法）`,
        `${cmd('market.dealSell({roomName, type, amount, length?, price?})')}：直接出售资源（对象参数写法）`,
        line(),
        sub('🤖', '自动交易'),
        `${cmd('market.auto.list(roomName?)')}：查看自动交易列表`,
        `${cmd('market.auto.status(roomName)')}：查看房间自动交易状态（阈值/库存/触发/订单）`,
        `${cmd('market.auto.remove(roomName, resourceType, orderType)')}：移除自动交易`,
        `${cmd('market.auto.buy(roomName, type?, resourceType, amount, price?)')}：设置自动求购（type: create / deal；不传默认 create；amount 支持 10k/2m；price 为最高价限制）`,
        `${cmd('market.auto.sell(roomName, type?, resourceType, amount, price?)')}：设置自动出售（type: create / deal；不传默认 create；amount 支持 10k/2m；price 为最低价限制）`,
        `${cmd('market.auto.buy({roomName, type?, resourceType, amount, price?})')}：设置自动求购（对象参数写法）`,
        `${cmd('market.auto.sell({roomName, type?, resourceType, amount, price?})')}：设置自动出售（对象参数写法）`,
        `${cmd('market.auto.createBuy(roomName, resourceType, amount, price?)')}：自动求购（create 快捷）`,
        `${cmd('market.auto.createSell(roomName, resourceType, amount, price?)')}：自动出售（create 快捷）`,
        `${cmd('market.auto.dealBuy(roomName, resourceType, amount, price?)')}：自动 Deal 买（快捷）`,
        `${cmd('market.auto.dealSell(roomName, resourceType, amount, price?)')}：自动 Deal 卖（快捷）`,
        line(),
    ].join(br),

    helpLab: [
        title('⚗️', 'Lab 指令列表'),
        line(),
        `${cmd('lab.open(roomName)')}：开启 Lab 合成`,
        `${cmd('lab.stop(roomName)')}：关闭 Lab 合成`,
        `${cmd('lab.set(roomName, product, amount?)')}：设置 Lab 合成底物`,
        `- 放置 flag：labA / lab-A 与 labB / lab-B 设置底物 Lab`,
        `- 不设置则会在lab数量造满时自动推导`,
        line(),
        `${cmd('lab.setboost(roomName)')}：设置 Boost Lab`,
        `- 放置 flag：labset-{资源类型} 在对应 Lab 上`,
        `${cmd('lab.addboost(roomName, mineral, amount?)')}：添加 Boost 任务`,
        `${cmd('lab.removeboost(roomName, mineral)')}：移除 Boost 任务`,
        line(),
        sub('🤖', '自动合成'),
        `${cmd('lab.auto.set(roomName, product, amount?)')}：设置自动合成（amount: 合成限额，0 为无限制）`,
        `${cmd('lab.auto.remove(roomName, product)')}：移除自动合成`,
        `${cmd('lab.auto.list(roomName?)')}：查看自动合成列表`,
        line(),
    ].join(br),

    helpFactory: [
        title('🏭', 'Factory 指令列表'),
        line(),
        `${cmd('factory.open(roomName)')}：开启 Factory`,
        `${cmd('factory.stop(roomName)')}：关闭 Factory`,
        `${cmd('factory.set(roomName, product, amount?)')}：设置生产任务`,
        line(),
        sub('🤖', '自动生产'),
        `${cmd('factory.auto.set(roomName, product, amount?)')}：设置自动生产`,
        `${cmd('factory.auto.remove(roomName, product)')}：移除自动生产`,
        `${cmd('factory.auto.list(roomName?)')}：查看自动生产列表`,
        line(),
    ].join(br),

    helpPower: [
        title('⚡', 'Power 指令列表'),
        line(),
        `${cmd('power.open(roomName?)')}：开启烧 Power（不填则全部房间）`,
        `${cmd('power.stop(roomName?)')}：关闭烧 Power（不填则全部房间）`,
        `${cmd('power.show(roomName)')}：查看 PowerSpawn 状态`,
        `${cmd('power.auto.on(roomName?)')}：切换到自动模式（不改阈值；不填则全部房间）`,
        `${cmd('power.auto.set(roomName?, energy, power)')}：设置自动烧 Power 阈值（不填则全部房间）`,
        `${cmd('power.auto.remove(roomName?)')}：移除自动烧 Power（不填则全部房间）`,
        line(),
        sub('🧙', 'PowerCreep'),
        `- PowerCreep 的“出生点/待机点”由旗帜控制（而不是控制台指令）：`,
        `- 放置旗帜 ${cmd('${pcname}-idle')} 或 ${cmd('${pcname}-IDLE')}：用于孵化房间与待机点（支持 idle/IDLE 大小写）`,
        `- 放置旗帜 ${cmd('${pcname}-home')}：作为回家点（operate 模式下优先回 home）`,
        `- 放置旗帜 ${cmd('${pcname}-move')}：强制移动到指定点（优先级最高）`,
        `- 放置旗帜 ${cmd('${pcname}-assist')}：进入支援模式（assist）`,
        line(),
    ].join(br),

    helpExpand: [
        title('🧭', '扩张指令列表'),
        line(),
        `- ${cmd("expand.set('shard/room' | 'room', 'shard/room' | 'room', {claimer?, builder?, carry?, upgrader?}?)")}：启动占领+援建计划（省略 shard 默认当前 shard）`,
        `- ${cmd('expand.list()')}：查看扩张计划`,
        `- ${cmd('expand.pause(idOrTarget)')}：暂停扩张计划`,
        `- ${cmd('expand.resume(idOrTarget)')}：恢复扩张计划`,
        `- ${cmd('expand.remove(idOrTarget)')}：删除扩张计划`,
        line(),
    ].join(br),

    helpSpawn: [
        title('🐣', '孵化指令列表'),
        line(),
        `${cmd('spawn.creep(roomName, bodypart, role, memory?)')}：孵化指定体型的 Creep（bodypart: 体型字符串）`,
        `${cmd('spawn.role(roomName, role, memory?, num?)')}：孵化指定角色的 Creep（使用默认体型）`,
        `${cmd('spawn.sign(roomName, targetRoom, sign)')}：孵化 scout 进行签名`,
        line(),
        sub('🚩', '旗帜孵化（每10tick扫描）'),
        `- 通用：${cmd('T-xx')} 是孵化间隔；${cmd('N-xx')} 是次数上限（部分旗默认一次性）`,
        line(),
        sub('⚔️', '战争孵化（warSpawn）'),
        `- ${cmd('AIO/<配置>/<孵化房>/T-间隔/N-数量')}：孵化 aio（配置支持 1T/2T/3T/6T；N 默认 0=一次性）`,
        `- ${cmd('CLEAN/<孵化房>/T-间隔')}：孵化 cleaner（持续触发，不自动删旗）`,
        `- ${cmd('ACLAIM/<孵化房>/T-间隔/N-数量')}：孵化 attack-claimer（持续触发，不自动删旗）`,
        `- ${cmd('DIS/<孵化房>/T-间隔/N-数量')}：孵化 dismantle（N 默认 0=一次性）`,
        `- ${cmd('LOOT/<孵化房>/B-T0~B-T3/T-间隔')}：孵化 logistic 回收资源（B-xx 为 boost 等级）`,
        `- LOOT 结束条件：boost 资源不足 / 目标房间可见且已无资源可搬运`,
        line(),
        sub('🆘', '援助/占领（aidSpawn）'),
        `- ${cmd('AID-BUILD/<孵化房>/S-来源房?/B-boost?/T-间隔')}：孵化 aid-build`,
        `- ${cmd('AID-UPGRADE/<孵化房>/B-boost?/T-间隔')}：孵化 aid-upgrade`,
        `- ${cmd('AID-UUP/<孵化房>/T-间隔')}：孵化 up-upgrade`,
        `- ${cmd('AID-ENERGY/<孵化房>/B-(T3|BIG)?/T-间隔')}：孵化 aid-carry 运能`,
        `- ${cmd('CLAIM/<孵化房>')}：占领流程（完成起房会自动删旗）`,
        `- ${cmd('RESERVE/<孵化房>/T-间隔')}：孵化 reserver（持续触发，不自动删旗）`,
        line(),
    ].join(br),

    helpTerminal: [
        title('📦', 'Terminal 指令列表'),
        line(),
        `${cmd('terminal.send(room?, target, type, amount)')}：发送资源（room 为空时从所有房间发送）`,
        `${cmd('terminal.show({roomName?, type?})')}：显示终端资源（可选参数组合查看不同范围）`,
        line(),
    ].join(br),

    helpResource: [
        title('🧰', '资源管理指令列表'),
        line(),
        `${cmd('resource.manage.set(roomName, resource, {source, target})')}：设置资源供需`,
        `- source：供应阈值（超过则可供应）`,
        `- target：需求阈值（低于则需要补充）`,
        `${cmd('resource.manage.remove(roomName, resource)')}：移除资源设置`,
        `${cmd('resource.manage.clear(roomName)')}：清空房间资源设置`,
        `${cmd('resource.manage.show.all()')}：显示所有资源设置`,
        `${cmd('resource.manage.show.room(roomName)')}：显示房间资源设置`,
        `${cmd('resource.manage.show.res(resource)')}：显示指定资源设置`,
        line(),
        sub('📦', '搬运任务'),
        `${cmd('resource.transport.task(roomName, source, target, resource, amount)')}：添加搬运任务（source/target: storage / terminal / factory）`,
        line(),
    ].join(br),

    helpOther: [
        title('🧾', '其他指令列表'),
        line(),
        sub('✅', '白名单'),
        `${cmd('whitelist.add(id)')}：添加玩家到白名单`,
        `${cmd('whitelist.remove(id)')}：从白名单移除玩家`,
        `${cmd('whitelist.show()')}：显示白名单`,
        line(),
        sub('🧹', '清理'),
        `${cmd('clear.site(roomName)')}：清除房间建筑工地`,
        `${cmd('clear.flag(roomName)')}：清除房间旗子`,
        `${cmd('clear.mission(roomName, type)')}：清空房间任务池`,
        `${cmd('clear.roomPath(roomName)')}：未实现（历史文案残留）`,
        `${cmd('clear.boostTask(roomName)')}：清空房间 Boost 任务`,
        line(),
        sub('🎛️', '开关'),
        `${cmd('warmode()')}：开关全局战争模式`,
        `${cmd('pixel()')}：开关搓 Pixel 功能`,
        `${cmd('stats()')}：开关信息统计功能`,
        line(),
        sub('🧭', '其他'),
        `${cmd('avoidRoom(room)')}：未实现（历史文案残留）`,
        line(),
        sub('💣', '核弹'),
        `${cmd('nuker.launch(...rooms)')}：发射核弹（放置 flag：nuke-{数量} 在目标位置）`,
        `${cmd('nuker.request(roomName, x, y, amount?, ttl?, ...rooms)')}：添加核弹请求（需要可见目标房间以创建 flag）`,
        `${cmd('nuker.list()')}：查看核弹请求队列`,
        `${cmd('nuker.cancel(id)')}：取消核弹请求（并移除对应 flag）`,
        `${cmd('nuker.cluster(roomName, count?, ...rooms)')}：在可见目标房间生成多点 nuke flags`,
        `${cmd('nuker.clear()')}：清除所有 nuke 发射标记`,
        line(),
    ].join(br),
};

/** 生成帮助命令配置 */
const createHelpCommand = (alias: string, withHead = false) => ({
    alias,
    exec: () => withHead ? `${head}${br}${helpTexts[alias]}` : helpTexts[alias],
});

export default [
    createHelpCommand('help', true),
    ...Object.keys(helpTexts)
        .filter(key => key !== 'help')
        .map(key => createHelpCommand(key)),
];
